#!/bin/sh
#
# Gradle start up script for POSIX generated by Gradle.
#
# Important: wrapper jar (gradle/wrapper/gradle-wrapper.jar) must be present.
# If it is missing, run `gradle wrapper` once, or just open the project in
# Android Studio which regenerates it on the first Gradle sync.

APP_HOME=$(cd "$(dirname "$0")" && pwd -P) || exit

DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'
CLASSPATH="$APP_HOME/gradle/wrapper/gradle-wrapper.jar"

if [ -n "$JAVA_HOME" ] ; then
    JAVACMD="$JAVA_HOME/bin/java"
else
    JAVACMD="java"
fi

exec "$JAVACMD" $DEFAULT_JVM_OPTS $JAVA_OPTS $GRADLE_OPTS \
    -classpath "$CLASSPATH" \
    org.gradle.wrapper.GradleWrapperMain "$@"
